#!/usr/bin/env python3
"""Add the ADR-0033 one-line install assets to a collected release (task L-007).

Given a release asset directory that already holds the per-OS archives
(`axiom-<version>-{windows-x64.zip,linux-x64.tar.gz,macos-x64.tar.gz}`), writes

* `install.ps1` and `install.sh` - generated by `packaging/oneline/generate_bootstrappers.py`
  with this tag, the archive names and their SHA-256 values;
* `channel.json` - the update channel manifest whose `release` block pins the tag and, per
  platform, the exact archive URL, SHA-256 and size (read by `axiom-cli update`);

then rewrites `SHA256SUMS` over every asset. Deterministic for the same inputs.

    python release/oneline_assets.py --assets <dir> --tag vX.Y.Z [--base-url <url>]
"""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CANONICAL = "https://github.com/orchex006/axiom-cli/releases/download"
PLATFORMS = (("windows-x64", "zip"), ("linux-x64", "tar.gz"), ("macos-x64", "tar.gz"))


def generator():
    spec = importlib.util.spec_from_file_location("gen", ROOT / "packaging/oneline/generate_bootstrappers.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def channel(tag: str, assets: Path, base_url: str, platforms) -> bytes:
    version = tag[1:]
    archives = []
    for platform, extension in platforms:
        name = f"axiom-{version}-{platform}.{extension}"
        path = assets / name
        archives.append({"platform": platform, "url": f"{base_url.rstrip('/')}/{tag}/{name}",
                         "sha256": sha(path), "size_bytes": path.stat().st_size})
    document = {"channel": "stable", "manifest_version": 1,
                "release": {"version": version, "tag": tag, "archives": archives},
                "note": "ADR-0033 one-line install channel; versions resolve only from this pinned release block."}
    return (json.dumps(document, indent=2, sort_keys=True) + "\n").encode()


def write_sums(assets: Path) -> None:
    rows = [f"{sha(p)}  {p.name}\n" for p in sorted(assets.iterdir()) if p.is_file() and p.name != "SHA256SUMS"]
    (assets / "SHA256SUMS").write_bytes("".join(rows).encode())


def build(assets: Path, tag: str, base_url: str = CANONICAL, platforms=PLATFORMS) -> None:
    gen = generator()
    version = tag[1:]
    missing = [f"axiom-{version}-{p}.{e}" for p, e in platforms if not (assets / f"axiom-{version}-{p}.{e}").is_file()]
    if missing:
        raise SystemExit(f"oneline_assets: missing archives {missing}")
    sums = "".join(f"{sha(assets / f'axiom-{version}-{p}.{e}')}  axiom-{version}-{p}.{e}\n" for p, e in PLATFORMS
                   if (assets / f"axiom-{version}-{p}.{e}").is_file())
    for p, e in PLATFORMS:  # the generator needs all three names; absent lanes get a refusing digest
        if not (assets / f"axiom-{version}-{p}.{e}").is_file():
            sums += f"{'0' * 64}  axiom-{version}-{p}.{e}\n"
    for name, data in gen.generate(tag, sums, base_url).items():
        (assets / name).write_bytes(data)
    (assets / "channel.json").write_bytes(channel(tag, assets, base_url, platforms))
    write_sums(assets)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--assets", type=Path, required=True)
    ap.add_argument("--tag", required=True)
    ap.add_argument("--base-url", default=CANONICAL)
    ap.add_argument("--platforms", default="windows-x64,linux-x64,macos-x64")
    args = ap.parse_args()
    wanted = set(args.platforms.split(","))
    build(args.assets, args.tag, args.base_url, tuple(x for x in PLATFORMS if x[0] in wanted))
    for line in (args.assets / "SHA256SUMS").read_text().splitlines():
        print(line)
    return 0


if __name__ == "__main__":
    sys.exit(main())
